# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: EDOT
description: >-
  Elastic Distributions of OpenTelemetry is an open-source ecosystem of tailored OpenTelemetry distributions,
  comprising an OpenTelemetry Collector and various OpenTelemetry Language SDKs.
  Each EDOT distribution is asssembled with carefully curated OpenTelemetry components,
  then rigorously tested to ensure production readiness. 
  This provides a reliable and optimized OpenTelemetry experience with Elastic,
  enabling seamless adoption with confidence and expert support.
baseurl: "/opentelemetry" # the subpath of your site, e.g. /blog
url: "https://elastic.github.io/opentelemetry/" # the base hostname & protocol for your site, e.g. http://example.com
logo: /images/edot.png
favicon_ico: "/images/favicon.ico"

# Build settings
theme: just-the-docs

color_scheme: elastic

collections:
  edot-collector:
    output: true
  edot-sdks:
    output: true

callouts:
  note:
    title: "Note"
    color: el_green
  warning:
    title: "Warning"
    color: yellow

just_the_docs:
  collections:
    edot-collector:
      name: EDOT Collector
      nav_fold: true
    edot-sdks:
      name: EDOT SDKs
      nav_fold: true
      nav_external_links:
        - title: EDOT Android
          url: https://www.elastic.co/guide/en/apm/agent/android/current/intro.html
          fa_icon_key: fa-brands fa-android
          hide_icon: false
          opens_in_new_tab: true
        - title: EDOT iOS
          url: https://www.elastic.co/guide/en/apm/agent/swift/current/intro.html
          fa_icon_key: fa-brands fa-apple
          hide_icon: false
          opens_in_new_tab: true
  nav_sort: case_insensitive

# ! DO NOT DELETE THE COMMENTS !
# -- EDOT versions start -- 
edot_versions:
  stack: 9.0.0
  collector: 9.0.0-rc1
  android: 1.0.0
  dotnet: 1.0.0
  ios:  1.0.0
  java: 1.3.0
  nodejs: 1.0.0
  php: 1.0.0
  python: 1.0.0
# -- EDOT versions end --

exclude:
  - vendor
  - "gen_edot_col_components/"

mermaid:
  # Version of mermaid library
  version: "11.5.0"

nav_external_links:
  - title: GitHub Repos
    url: https://github.com/elastic/opentelemetry
    fa_icon_key: fa-brands fa-github
    hide_icon: false
    opens_in_new_tab: true
